import type {
  Clinic,
  ClinicApplication,
  DashboardSummary,
  GrowthPoint,
  Patient,
  RevenuePoint,
  Ticket,
} from "@/types";

export const dashboardSummary: DashboardSummary = {
  totalPatients: 18432,
  patientDelta: 12.4,
  pendingApplications: 7,
  applicationDelta: -3,
  platformRevenue: 2846500,
  revenueDelta: 18.9,
  activeAppointments: 342,
  completedAppointments: 9187,
  appointmentDelta: 7.6,
  activeClinics: 48,
  openTickets: 5,
};

export const growthData: GrowthPoint[] = [
  { label: "Oca", patients: 9400, clinics: 22 },
  { label: "Şub", patients: 10250, clinics: 26 },
  { label: "Mar", patients: 11800, clinics: 29 },
  { label: "Nis", patients: 12950, clinics: 33 },
  { label: "May", patients: 14100, clinics: 37 },
  { label: "Haz", patients: 15600, clinics: 41 },
  { label: "Tem", patients: 16850, clinics: 44 },
  { label: "Ağu", patients: 18432, clinics: 48 },
];

export const revenueData: RevenuePoint[] = [
  { label: "Oca", revenue: 1180000, commission: 141600 },
  { label: "Şub", revenue: 1320000, commission: 158400 },
  { label: "Mar", revenue: 1595000, commission: 191400 },
  { label: "Nis", revenue: 1740000, commission: 208800 },
  { label: "May", revenue: 1980000, commission: 237600 },
  { label: "Haz", revenue: 2210000, commission: 265200 },
  { label: "Tem", revenue: 2540000, commission: 304800 },
  { label: "Ağu", revenue: 2846500, commission: 341580 },
];

export const specialtyDemand: { name: string; value: number }[] = [
  { name: "Saç Ekimi", value: 34 },
  { name: "Diş Tedavisi", value: 26 },
  { name: "Estetik Cerrahi", value: 18 },
  { name: "Göz (LASIK)", value: 12 },
  { name: "Tüp Bebek (IVF)", value: 10 },
];

export const clinicApplications: ClinicApplication[] = [
  {
    id: "APP-2048",
    clinicName: "Estetik International Hospital",
    contactName: "Dr. Kerem Aksoy",
    contactRole: "Başhekim",
    email: "basvuru@estetikinternational.com",
    phone: "+90 212 555 18 42",
    city: "İstanbul",
    country: "Türkiye",
    countryCode: "TR",
    specialties: ["Saç Ekimi", "Estetik Cerrahi", "Cilt Bakımı"],
    taxId: "4820193756",
    bedCount: 40,
    foundedYear: 2014,
    website: "estetikinternational.com",
    about:
      "İstanbul merkezli, uluslararası hastalara saç ekimi ve estetik cerrahi hizmeti veren JCI adayı özel hastane.",
    submittedAt: "2026-07-08T09:12:00Z",
    status: "pending",
    documents: [
      {
        id: "d1",
        label: "Vergi Levhası",
        type: "tax",
        fileName: "vergi-levhasi-2026.pdf",
        fileSizeKb: 512,
        status: "verified",
      },
      {
        id: "d2",
        label: "JCI Akreditasyon Belgesi",
        type: "accreditation",
        fileName: "jci-certificate.pdf",
        fileSizeKb: 1840,
        status: "unverified",
      },
      {
        id: "d3",
        label: "Sağlık Bakanlığı Ruhsatı",
        type: "license",
        fileName: "saglik-ruhsat.pdf",
        fileSizeKb: 980,
        status: "verified",
      },
    ],
  },
  {
    id: "APP-2049",
    clinicName: "DentalPark Ağız ve Diş Sağlığı",
    contactName: "Ayşe Demirtaş",
    contactRole: "Klinik Müdürü",
    email: "info@dentalpark.com.tr",
    phone: "+90 232 444 09 21",
    city: "İzmir",
    country: "Türkiye",
    countryCode: "TR",
    specialties: ["Diş Tedavisi", "İmplant", "Ortodonti"],
    taxId: "6172038491",
    bedCount: 12,
    foundedYear: 2018,
    website: "dentalpark.com.tr",
    about:
      "Ege bölgesinde diş implantı ve gülüş tasarımı alanında uzmanlaşmış poliklinik.",
    submittedAt: "2026-07-07T14:30:00Z",
    status: "pending",
    documents: [
      {
        id: "d1",
        label: "Vergi Levhası",
        type: "tax",
        fileName: "vergi-2026.pdf",
        fileSizeKb: 445,
        status: "verified",
      },
      {
        id: "d2",
        label: "Poliklinik Ruhsatı",
        type: "license",
        fileName: "poliklinik-ruhsat.pdf",
        fileSizeKb: 720,
        status: "unverified",
      },
    ],
  },
  {
    id: "APP-2050",
    clinicName: "VisionCare Göz Merkezi",
    contactName: "Op. Dr. Mert Şahin",
    contactRole: "Kurucu Ortak",
    email: "kurumsal@visioncare.com",
    phone: "+90 312 466 77 88",
    city: "Ankara",
    country: "Türkiye",
    countryCode: "TR",
    specialties: ["Göz (LASIK)", "Katarakt", "Retina"],
    taxId: "9081726354",
    bedCount: 8,
    foundedYear: 2020,
    website: "visioncare.com",
    about:
      "LASIK ve akıllı lens tedavilerinde uzman, son teknoloji cihazlarla donatılmış göz merkezi.",
    submittedAt: "2026-07-06T11:05:00Z",
    status: "pending",
    documents: [
      {
        id: "d1",
        label: "Vergi Levhası",
        type: "tax",
        fileName: "vergi-levhasi.pdf",
        fileSizeKb: 388,
        status: "verified",
      },
      {
        id: "d2",
        label: "ISO 9001 Sertifikası",
        type: "accreditation",
        fileName: "iso-9001.pdf",
        fileSizeKb: 1120,
        status: "verified",
      },
      {
        id: "d3",
        label: "Mesuliyet Sigortası",
        type: "insurance",
        fileName: "sigorta-police.pdf",
        fileSizeKb: 640,
        status: "unverified",
      },
    ],
  },
  {
    id: "APP-2051",
    clinicName: "NovaFertility Tüp Bebek Merkezi",
    contactName: "Prof. Dr. Elif Korkmaz",
    contactRole: "Tıbbi Direktör",
    email: "iletisim@novafertility.com",
    phone: "+90 216 333 55 66",
    city: "İstanbul",
    country: "Türkiye",
    countryCode: "TR",
    specialties: ["Tüp Bebek (IVF)", "Kadın Doğum"],
    taxId: "3345678219",
    bedCount: 20,
    foundedYear: 2016,
    website: "novafertility.com",
    about:
      "Uluslararası çiftlere yüksek başarı oranıyla tüp bebek ve üreme sağlığı hizmeti sunar.",
    submittedAt: "2026-07-05T08:45:00Z",
    status: "pending",
    documents: [
      {
        id: "d1",
        label: "Vergi Levhası",
        type: "tax",
        fileName: "vergi.pdf",
        fileSizeKb: 401,
        status: "verified",
      },
      {
        id: "d2",
        label: "JCI Akreditasyon Belgesi",
        type: "accreditation",
        fileName: "jci.pdf",
        fileSizeKb: 2010,
        status: "verified",
      },
    ],
  },
  {
    id: "APP-2044",
    clinicName: "Antalya Med Wellness",
    contactName: "Selçuk Yaman",
    contactRole: "Genel Müdür",
    email: "info@antalyamed.com",
    phone: "+90 242 111 22 33",
    city: "Antalya",
    country: "Türkiye",
    countryCode: "TR",
    specialties: ["Fizik Tedavi", "Wellness"],
    taxId: "7788990011",
    bedCount: 30,
    foundedYear: 2012,
    website: "antalyamed.com",
    about: "Sağlık turizmi odaklı rehabilitasyon ve wellness merkezi.",
    submittedAt: "2026-07-01T10:00:00Z",
    status: "approved",
    documents: [
      {
        id: "d1",
        label: "Vergi Levhası",
        type: "tax",
        fileName: "vergi.pdf",
        fileSizeKb: 360,
        status: "verified",
      },
    ],
  },
  {
    id: "APP-2039",
    clinicName: "QuickCare Poliklinik",
    contactName: "Hasan Öztürk",
    contactRole: "Sahip",
    email: "hasan@quickcare.com",
    phone: "+90 224 999 88 77",
    city: "Bursa",
    country: "Türkiye",
    countryCode: "TR",
    specialties: ["Genel Cerrahi"],
    taxId: "1231231231",
    bedCount: 6,
    foundedYear: 2023,
    website: "quickcare.com",
    about: "Küçük ölçekli genel cerrahi polikliniği.",
    submittedAt: "2026-06-27T16:20:00Z",
    status: "rejected",
    documents: [
      {
        id: "d1",
        label: "Vergi Levhası",
        type: "tax",
        fileName: "vergi.pdf",
        fileSizeKb: 290,
        status: "unverified",
      },
    ],
  },
];

export const clinics: Clinic[] = [
  {
    id: "CLN-001",
    name: "Acıbadem Sağlık Grubu",
    city: "İstanbul",
    country: "Türkiye",
    countryCode: "TR",
    specialties: ["Onkoloji", "Kardiyoloji", "Estetik Cerrahi"],
    doctorCount: 42,
    rating: 4.9,
    reviewCount: 1284,
    monthlyPatients: 2140,
    completedAppointments: 3120,
    revenueContribution: 684000,
    status: "active",
    featured: true,
    joinedAt: "2025-01-15T00:00:00Z",
    accreditation: ["JCI", "ISO 9001"],
    doctors: [
      { id: "DOC-1", name: "Prof. Dr. Cem Yıldırım", specialty: "Kardiyoloji", status: "active", rating: 4.9 },
      { id: "DOC-2", name: "Op. Dr. Deniz Arı", specialty: "Estetik Cerrahi", status: "active", rating: 4.8 },
      { id: "DOC-3", name: "Dr. Leyla Toprak", specialty: "Onkoloji", status: "passive", rating: 4.7 },
    ],
  },
  {
    id: "CLN-002",
    name: "Estetik International Hospital",
    city: "İstanbul",
    country: "Türkiye",
    countryCode: "TR",
    specialties: ["Saç Ekimi", "Estetik Cerrahi"],
    doctorCount: 18,
    rating: 4.7,
    reviewCount: 642,
    monthlyPatients: 980,
    completedAppointments: 1450,
    revenueContribution: 412000,
    status: "active",
    featured: true,
    joinedAt: "2025-03-02T00:00:00Z",
    accreditation: ["JCI"],
    doctors: [
      { id: "DOC-4", name: "Dr. Kerem Aksoy", specialty: "Saç Ekimi", status: "active", rating: 4.8 },
      { id: "DOC-5", name: "Op. Dr. Sinem Ak", specialty: "Estetik Cerrahi", status: "active", rating: 4.6 },
    ],
  },
  {
    id: "CLN-003",
    name: "DentalPark Ağız ve Diş Sağlığı",
    city: "İzmir",
    country: "Türkiye",
    countryCode: "TR",
    specialties: ["Diş Tedavisi", "İmplant", "Ortodonti"],
    doctorCount: 12,
    rating: 4.8,
    reviewCount: 908,
    monthlyPatients: 1320,
    completedAppointments: 1980,
    revenueContribution: 356000,
    status: "active",
    featured: false,
    joinedAt: "2025-04-18T00:00:00Z",
    accreditation: ["ISO 9001"],
    doctors: [
      { id: "DOC-6", name: "Dt. Ayşe Demirtaş", specialty: "Ortodonti", status: "active", rating: 4.9 },
      { id: "DOC-7", name: "Dt. Emre Kaya", specialty: "İmplant", status: "active", rating: 4.7 },
    ],
  },
  {
    id: "CLN-004",
    name: "VisionCare Göz Merkezi",
    city: "Ankara",
    country: "Türkiye",
    countryCode: "TR",
    specialties: ["Göz (LASIK)", "Katarakt"],
    doctorCount: 8,
    rating: 4.6,
    reviewCount: 421,
    monthlyPatients: 560,
    completedAppointments: 820,
    revenueContribution: 198000,
    status: "passive",
    featured: false,
    joinedAt: "2025-06-09T00:00:00Z",
    accreditation: ["ISO 9001"],
    doctors: [
      { id: "DOC-8", name: "Op. Dr. Mert Şahin", specialty: "Göz (LASIK)", status: "active", rating: 4.6 },
    ],
  },
  {
    id: "CLN-005",
    name: "NovaFertility Tüp Bebek Merkezi",
    city: "İstanbul",
    country: "Türkiye",
    countryCode: "TR",
    specialties: ["Tüp Bebek (IVF)", "Kadın Doğum"],
    doctorCount: 15,
    rating: 4.9,
    reviewCount: 517,
    monthlyPatients: 430,
    completedAppointments: 610,
    revenueContribution: 289000,
    status: "active",
    featured: true,
    joinedAt: "2025-02-27T00:00:00Z",
    accreditation: ["JCI", "ISO 9001"],
    doctors: [
      { id: "DOC-9", name: "Prof. Dr. Elif Korkmaz", specialty: "Tüp Bebek (IVF)", status: "active", rating: 5.0 },
      { id: "DOC-10", name: "Dr. Gökhan Er", specialty: "Kadın Doğum", status: "active", rating: 4.8 },
    ],
  },
];

export const patients: Patient[] = [
  {
    id: "PAT-10231",
    name: "Ahmed Al-Farsi",
    email: "ahmed.alfarsi@gmail.com",
    phone: "+968 91 234 567",
    country: "Umman",
    countryCode: "OM",
    status: "active",
    appointments: 3,
    totalSpend: 84000,
    joinedAt: "2026-02-11T00:00:00Z",
    lastActiveAt: "2026-07-08T18:20:00Z",
  },
  {
    id: "PAT-10232",
    name: "Amina Haddad",
    email: "amina.haddad@outlook.com",
    phone: "+961 3 445 118",
    country: "Lübnan",
    countryCode: "LB",
    status: "active",
    appointments: 2,
    totalSpend: 42500,
    joinedAt: "2026-03-04T00:00:00Z",
    lastActiveAt: "2026-07-09T09:40:00Z",
  },
  {
    id: "PAT-10233",
    name: "James Whitmore",
    email: "j.whitmore@proton.me",
    phone: "+44 7700 900321",
    country: "Birleşik Krallık",
    countryCode: "GB",
    status: "active",
    appointments: 5,
    totalSpend: 156000,
    joinedAt: "2025-11-19T00:00:00Z",
    lastActiveAt: "2026-07-07T14:10:00Z",
  },
  {
    id: "PAT-10234",
    name: "Sofia Rossi",
    email: "sofia.rossi@gmail.com",
    phone: "+39 320 118 4472",
    country: "İtalya",
    countryCode: "IT",
    status: "inactive",
    appointments: 1,
    totalSpend: 12000,
    joinedAt: "2026-01-22T00:00:00Z",
    lastActiveAt: "2026-05-02T11:00:00Z",
  },
  {
    id: "PAT-10235",
    name: "Mohammed Al-Rashid",
    email: "m.alrashid@gmail.com",
    phone: "+966 55 987 6543",
    country: "Suudi Arabistan",
    countryCode: "SA",
    status: "active",
    appointments: 4,
    totalSpend: 98500,
    joinedAt: "2025-12-30T00:00:00Z",
    lastActiveAt: "2026-07-09T20:05:00Z",
  },
  {
    id: "PAT-10236",
    name: "Elena Petrova",
    email: "elena.petrova@yandex.ru",
    phone: "+7 903 555 2211",
    country: "Rusya",
    countryCode: "RU",
    status: "banned",
    appointments: 0,
    totalSpend: 0,
    joinedAt: "2026-04-15T00:00:00Z",
    lastActiveAt: "2026-04-16T08:30:00Z",
  },
  {
    id: "PAT-10237",
    name: "David Müller",
    email: "d.mueller@web.de",
    phone: "+49 151 234 5678",
    country: "Almanya",
    countryCode: "DE",
    status: "active",
    appointments: 2,
    totalSpend: 61000,
    joinedAt: "2026-05-06T00:00:00Z",
    lastActiveAt: "2026-07-06T16:45:00Z",
  },
  {
    id: "PAT-10238",
    name: "Fatima Zahra",
    email: "fatima.zahra@gmail.com",
    phone: "+212 661 445 990",
    country: "Fas",
    countryCode: "MA",
    status: "active",
    appointments: 1,
    totalSpend: 23000,
    joinedAt: "2026-06-18T00:00:00Z",
    lastActiveAt: "2026-07-08T10:15:00Z",
  },
];

export const tickets: Ticket[] = [
  {
    id: "TCK-5521",
    subject: "Randevu onayı gelmedi",
    requesterName: "Ahmed Al-Farsi",
    requesterType: "patient",
    category: "Randevu",
    priority: "high",
    status: "open",
    createdAt: "2026-07-09T08:30:00Z",
    message:
      "Estetik International'da saç ekimi için randevu talebi oluşturdum ancak 24 saattir onay bilgisi almadım. Uçuşumu planlamam gerekiyor.",
  },
  {
    id: "TCK-5520",
    subject: "Komisyon faturası talebi",
    requesterName: "DentalPark Ağız ve Diş Sağlığı",
    requesterType: "clinic",
    category: "Faturalandırma",
    priority: "medium",
    status: "open",
    createdAt: "2026-07-08T13:12:00Z",
    message:
      "Haziran ayına ait platform komisyon faturamızı muhasebe sisteminde göremiyoruz. Resmi faturayı iletebilir misiniz?",
  },
  {
    id: "TCK-5518",
    subject: "Profil fotoğrafı güncellenmiyor",
    requesterName: "VisionCare Göz Merkezi",
    requesterType: "clinic",
    category: "Teknik",
    priority: "low",
    status: "pending",
    createdAt: "2026-07-07T09:50:00Z",
    message:
      "Vitrin görselimizi güncelledik ancak arama sonuçlarında hâlâ eski görsel görünüyor.",
  },
  {
    id: "TCK-5515",
    subject: "İade ve iptal süreci",
    requesterName: "Sofia Rossi",
    requesterType: "patient",
    category: "Ödeme",
    priority: "high",
    status: "pending",
    createdAt: "2026-07-06T17:05:00Z",
    message:
      "İptal ettiğim diş tedavisi randevusunun ön ödemesi hesabıma yansımadı. Süreç ne kadar sürüyor?",
  },
  {
    id: "TCK-5509",
    subject: "Doktor profili doğrulama",
    requesterName: "NovaFertility Tüp Bebek Merkezi",
    requesterType: "clinic",
    category: "Hesap",
    priority: "medium",
    status: "resolved",
    createdAt: "2026-07-03T11:40:00Z",
    message:
      "Yeni katılan doktorumuzun diploma doğrulaması tamamlandı mı? Vitrinde 'onay bekliyor' görünüyor.",
  },
  {
    id: "TCK-5504",
    subject: "Uygulama bildirimleri gelmiyor",
    requesterName: "James Whitmore",
    requesterType: "patient",
    category: "Teknik",
    priority: "low",
    status: "resolved",
    createdAt: "2026-06-30T20:15:00Z",
    message: "Mobil uygulamada mesaj bildirimleri iOS'ta çalışmıyor.",
  },
];

export function getApplicationById(id: string): ClinicApplication | undefined {
  return clinicApplications.find((app) => app.id === id);
}

export function getClinicById(id: string): Clinic | undefined {
  return clinics.find((clinic) => clinic.id === id);
}
