import type { ClinicMetrics, Doctor, PatientLead } from "@/types";

export function countryCodeToFlagEmoji(countryCode: string): string {
  return countryCode
    .toUpperCase()
    .replace(/./g, (char) =>
      String.fromCodePoint(127397 + char.charCodeAt(0))
    );
}

export const BRANCHES = [
  "Saç Ekimi",
  "Estetik Cerrahi",
  "Diş Tedavisi",
  "Göz (LASIK)",
  "Bariatrik Cerrahi",
  "Ortopedi",
  "Tüp Bebek (IVF)",
  "Kardiyoloji",
] as const;

export const patientLeads: PatientLead[] = [
  {
    id: "LD-1042",
    fullName: "Klaus Richter",
    country: "Almanya",
    countryCode: "DE",
    branch: "Saç Ekimi",
    requestedDate: "2026-07-08",
    createdAt: "2026-07-04T08:12:00",
    status: "BEKLEMEDE",
    hasVipTransfer: true,
    needsHotel: true,
    phone: "+49 176 2231 8890",
    email: "klaus.richter@example.de",
    documents: [
      { id: "DOC-1", type: "PASAPORT", fileName: "passport_klaus.pdf", uploadedAt: "2026-07-03", fileSizeKb: 842 },
      { id: "DOC-2", type: "TIBBI_RAPOR", fileName: "kan_tahlili_klaus.pdf", uploadedAt: "2026-07-03", fileSizeKb: 1203 },
    ],
  },
  {
    id: "LD-1041",
    fullName: "Fatima Al-Sayed",
    country: "Suudi Arabistan",
    countryCode: "SA",
    branch: "Estetik Cerrahi",
    requestedDate: "2026-07-10",
    createdAt: "2026-07-04T07:40:00",
    status: "ONAYLANDI",
    hasVipTransfer: true,
    needsHotel: true,
    phone: "+966 50 123 4567",
    email: "fatima.alsayed@example.sa",
    assignedDoctor: "Op. Dr. Elif Yılmaz",
    documents: [
      { id: "DOC-3", type: "PASAPORT", fileName: "passport_fatima.pdf", uploadedAt: "2026-07-02", fileSizeKb: 765 },
      { id: "DOC-4", type: "VIZE", fileName: "vize_fatima.pdf", uploadedAt: "2026-07-02", fileSizeKb: 511 },
    ],
  },
  {
    id: "LD-1040",
    fullName: "Igor Petrov",
    country: "Rusya",
    countryCode: "RU",
    branch: "Diş Tedavisi",
    requestedDate: "2026-07-06",
    createdAt: "2026-07-04T06:55:00",
    status: "BEKLEMEDE",
    hasVipTransfer: false,
    needsHotel: false,
    phone: "+7 916 234 5566",
    email: "igor.petrov@example.ru",
    documents: [
      { id: "DOC-5", type: "PASAPORT", fileName: "passport_igor.pdf", uploadedAt: "2026-07-01", fileSizeKb: 690 },
    ],
  },
  {
    id: "LD-1039",
    fullName: "James Whitfield",
    country: "Birleşik Krallık",
    countryCode: "GB",
    branch: "Göz (LASIK)",
    requestedDate: "2026-07-05",
    createdAt: "2026-07-03T21:14:00",
    status: "REDDEDİLDİ",
    hasVipTransfer: false,
    needsHotel: true,
    phone: "+44 7700 900123",
    email: "james.whitfield@example.co.uk",
    notes: "Uygun tarih bulunamadı, hasta başka klinik ile görüşüyor.",
    documents: [
      { id: "DOC-6", type: "PASAPORT", fileName: "passport_james.pdf", uploadedAt: "2026-06-30", fileSizeKb: 588 },
    ],
  },
  {
    id: "LD-1038",
    fullName: "Amina Haddad",
    country: "Irak",
    countryCode: "IQ",
    branch: "Bariatrik Cerrahi",
    requestedDate: "2026-07-12",
    createdAt: "2026-07-03T18:02:00",
    status: "ONAYLANDI",
    hasVipTransfer: true,
    needsHotel: true,
    phone: "+964 770 123 4567",
    email: "amina.haddad@example.iq",
    assignedDoctor: "Prof. Dr. Mehmet Kaya",
    documents: [
      { id: "DOC-7", type: "PASAPORT", fileName: "passport_amina.pdf", uploadedAt: "2026-07-01", fileSizeKb: 720 },
      { id: "DOC-8", type: "TIBBI_RAPOR", fileName: "rapor_amina.pdf", uploadedAt: "2026-07-02", fileSizeKb: 980 },
      { id: "DOC-9", type: "SIGORTA", fileName: "sigorta_amina.pdf", uploadedAt: "2026-07-02", fileSizeKb: 410 },
    ],
  },
  {
    id: "LD-1037",
    fullName: "Youssef Ben Ali",
    country: "Libya",
    countryCode: "LY",
    branch: "Ortopedi",
    requestedDate: "2026-07-09",
    createdAt: "2026-07-03T15:47:00",
    status: "BEKLEMEDE",
    hasVipTransfer: false,
    needsHotel: true,
    phone: "+218 91 234 5678",
    email: "youssef.benali@example.ly",
    documents: [
      { id: "DOC-10", type: "PASAPORT", fileName: "passport_youssef.pdf", uploadedAt: "2026-07-01", fileSizeKb: 655 },
    ],
  },
  {
    id: "LD-1036",
    fullName: "Sophie Bernard",
    country: "Fransa",
    countryCode: "FR",
    branch: "Estetik Cerrahi",
    requestedDate: "2026-07-07",
    createdAt: "2026-07-03T11:30:00",
    status: "ONAYLANDI",
    hasVipTransfer: true,
    needsHotel: false,
    phone: "+33 6 12 34 56 78",
    email: "sophie.bernard@example.fr",
    assignedDoctor: "Op. Dr. Elif Yılmaz",
    documents: [
      { id: "DOC-11", type: "PASAPORT", fileName: "passport_sophie.pdf", uploadedAt: "2026-07-02", fileSizeKb: 702 },
    ],
  },
  {
    id: "LD-1035",
    fullName: "Ahmed Al-Farsi",
    country: "Katar",
    countryCode: "QA",
    branch: "Tüp Bebek (IVF)",
    requestedDate: "2026-07-14",
    createdAt: "2026-07-02T09:18:00",
    status: "BEKLEMEDE",
    hasVipTransfer: true,
    needsHotel: true,
    phone: "+974 5512 3456",
    email: "ahmed.alfarsi@example.qa",
    documents: [
      { id: "DOC-12", type: "PASAPORT", fileName: "passport_ahmed.pdf", uploadedAt: "2026-06-29", fileSizeKb: 810 },
      { id: "DOC-13", type: "TIBBI_RAPOR", fileName: "rapor_ahmed.pdf", uploadedAt: "2026-06-30", fileSizeKb: 1340 },
    ],
  },
  {
    id: "LD-1034",
    fullName: "Laura van Dijk",
    country: "Hollanda",
    countryCode: "NL",
    branch: "Diş Tedavisi",
    requestedDate: "2026-07-06",
    createdAt: "2026-07-02T08:05:00",
    status: "ONAYLANDI",
    hasVipTransfer: false,
    needsHotel: false,
    phone: "+31 6 1234 5678",
    email: "laura.vandijk@example.nl",
    assignedDoctor: "Dt. Can Öztürk",
    documents: [
      { id: "DOC-14", type: "PASAPORT", fileName: "passport_laura.pdf", uploadedAt: "2026-06-28", fileSizeKb: 640 },
    ],
  },
  {
    id: "LD-1033",
    fullName: "Robert Miller",
    country: "Amerika Birleşik Devletleri",
    countryCode: "US",
    branch: "Kardiyoloji",
    requestedDate: "2026-07-11",
    createdAt: "2026-07-01T14:20:00",
    status: "BEKLEMEDE",
    hasVipTransfer: true,
    needsHotel: true,
    phone: "+1 305 234 5678",
    email: "robert.miller@example.com",
    documents: [
      { id: "DOC-15", type: "PASAPORT", fileName: "passport_robert.pdf", uploadedAt: "2026-06-27", fileSizeKb: 730 },
      { id: "DOC-16", type: "TIBBI_RAPOR", fileName: "ekg_robert.pdf", uploadedAt: "2026-06-28", fileSizeKb: 1580 },
    ],
  },
];

export const doctors: Doctor[] = [
  {
    id: "DR-01",
    fullName: "Elif Yılmaz",
    title: "Op. Dr.",
    specialty: "Estetik, Plastik ve Rekonstrüktif Cerrahi",
    languages: ["TR", "EN", "AR"],
    status: "MÜSAİT",
    workingHours: { start: "09:00", end: "17:00" },
    patientsToday: 4,
    yearsExperience: 14,
    avatarInitials: "EY",
  },
  {
    id: "DR-02",
    fullName: "Mehmet Kaya",
    title: "Prof. Dr.",
    specialty: "Genel Cerrahi (Bariatrik)",
    languages: ["TR", "EN", "RU"],
    status: "DOLU",
    workingHours: { start: "08:00", end: "16:00" },
    patientsToday: 3,
    yearsExperience: 21,
    avatarInitials: "MK",
  },
  {
    id: "DR-03",
    fullName: "Can Öztürk",
    title: "Dt.",
    specialty: "Ağız, Diş ve Çene Cerrahisi",
    languages: ["TR", "EN", "DE"],
    status: "MÜSAİT",
    workingHours: { start: "09:30", end: "18:00" },
    patientsToday: 6,
    yearsExperience: 9,
    avatarInitials: "CÖ",
  },
  {
    id: "DR-04",
    fullName: "Zeynep Arslan",
    title: "Doç. Dr.",
    specialty: "Göz Hastalıkları (LASIK & Kornea)",
    languages: ["TR", "EN", "FR"],
    status: "MOLADA",
    workingHours: { start: "09:00", end: "17:30" },
    patientsToday: 2,
    yearsExperience: 12,
    avatarInitials: "ZA",
  },
  {
    id: "DR-05",
    fullName: "Burak Demir",
    title: "Op. Dr.",
    specialty: "Saç Ekimi ve Dermatoloji",
    languages: ["TR", "EN", "AR", "RU"],
    status: "DOLU",
    workingHours: { start: "08:30", end: "16:30" },
    patientsToday: 8,
    yearsExperience: 11,
    avatarInitials: "BD",
  },
  {
    id: "DR-06",
    fullName: "Selin Aydın",
    title: "Uzm. Dr.",
    specialty: "Kadın Hastalıkları ve Tüp Bebek (IVF)",
    languages: ["TR", "EN", "AR"],
    status: "MÜSAİT",
    workingHours: { start: "10:00", end: "18:00" },
    patientsToday: 3,
    yearsExperience: 16,
    avatarInitials: "SA",
  },
  {
    id: "DR-07",
    fullName: "Ozan Şahin",
    title: "Prof. Dr.",
    specialty: "Ortopedi ve Travmatoloji",
    languages: ["TR", "EN", "DE", "RU"],
    status: "MÜSAİT",
    workingHours: { start: "09:00", end: "17:00" },
    patientsToday: 5,
    yearsExperience: 19,
    avatarInitials: "OŞ",
  },
  {
    id: "DR-08",
    fullName: "Deniz Koç",
    title: "Doç. Dr.",
    specialty: "Kardiyoloji",
    languages: ["TR", "EN"],
    status: "MOLADA",
    workingHours: { start: "08:00", end: "15:00" },
    patientsToday: 4,
    yearsExperience: 15,
    avatarInitials: "DK",
  },
];

export function getClinicMetrics(leads: PatientLead[]): ClinicMetrics {
  const todayLeads = leads.length;
  const approvedCount = leads.filter((l) => l.status === "ONAYLANDI").length;
  const activeDoctors = doctors.filter((d) => d.status !== "DOLU").length;
  const conversionRate = todayLeads
    ? Math.round((approvedCount / todayLeads) * 100)
    : 0;

  return {
    todayLeads,
    approvedCount,
    activeDoctors,
    conversionRate,
    liveQueueMinutes: 12,
  };
}
