import type { PreviewsContent } from "./previews";
import type { ScreensContent } from "./screens";

export type Locale = "en" | "tr";

export type NavLink = { href: string; label: string };

export type LegalDoc = {
  title: string;
  intro: string;
  updated: string;
  sections: { heading: string; body: string }[];
};

export type LeadCopy = {
  close: string;
  patientTab: string;
  clinicTab: string;
  patientTitle: string;
  clinicTitle: string;
  patientBody: string;
  clinicBody: string;
  successTitle: string;
  successBody: string;
  name: string;
  namePlaceholder: string;
  email: string;
  emailPlaceholder: string;
  phone: string;
  phonePlaceholder: string;
  country: string;
  countryPlaceholder: string;
  treatment: string;
  selectTreatment: string;
  treatmentOptions: string[];
  clinicName: string;
  clinicNamePlaceholder: string;
  city: string;
  cityPlaceholder: string;
  website: string;
  websitePlaceholder: string;
  role: string;
  roleClinic: string;
  roleDoctor: string;
  message: string;
  messagePlaceholder: string;
  consent: string;
  privacyLink: string;
  error: string;
  errorNetwork: string;
  errorServer: string;
  submitting: string;
  submit: string;
  required: string;
  dataNote: string;
};

export type SiteContent = {
  seo: { title: string; description: string; keywords: string[] };
  notFound: { title: string; body: string; cta: string };
  lead: LeadCopy;
  nav: {
    links: NavLink[];
    solutionsLabel: string;
    solutions: { href: string; label: string; desc: string }[];
    clinicCta: string;
    openMenu: string;
    closeMenu: string;
    localeEn: string;
    localeTr: string;
    skip: string;
    getStarted: string;
    menu: string;
    pages: string;
    language: string;
    languageAria: string;
  };
  contact: {
    seoTitle: string;
    eyebrow: string;
    title: string;
    intro: string;
    patientTab: string;
    clinicTab: string;
    name: string;
    email: string;
    phone: string;
    topic: string;
    message: string;
    submit: string;
    submitting: string;
    successTitle: string;
    successBody: string;
    phoneTitle: string;
    emailTitle: string;
    addressTitle: string;
    privacyNote: string;
    sendAnother: string;
    namePlaceholder: string;
    emailPlaceholder: string;
    phonePlaceholder: string;
    channelsTitle: string;
    teamInbox: string;
    avgResponse: string;
    topicPlaceholderPatient: string;
    topicPlaceholderClinic: string;
    messagePlaceholder: string;
    responseNote: string;
    error: string;
    errorNetwork: string;
    errorServer: string;
  };
  home: {
    audiencePatient: string;
    audienceClinic: string;
    patient: {
      headline: string;
      headlineAccent: string;
      subcopy: string;
      primaryCta: string;
      secondaryCta: string;
      previewCaption: string;
    };
    clinic: {
      headline: string;
      headlineAccent: string;
      subcopy: string;
      primaryCta: string;
      secondaryCta: string;
      previewCaption: string;
    };
    proof: { kicker: string; title: string }[];
    match: {
      eyebrow: string;
      title: string;
      body: string;
      patientLabel: string;
      clinicLabel: string;
      matchBadge: string;
      noBroker: string;
      patientTags: string[];
      clinicTags: string[];
    };
    doorsEyebrow: string;
    doorsTitle: string;
    doors: {
      href: string;
      eyebrow: string;
      title: string;
      body: string;
      preview: "clinic" | "patient" | "doctor";
    }[];
    trust: { label: string; detail: string }[];
    trustStripLabel: string;
    globalReach: {
      eyebrow: string;
      title: string;
      subtitle: string;
      panelTitle: string;
      panelSubtitle: string;
      demoCaption: string;
      countryColumn: string;
      patientColumn: string;
      emptyList: string;
      zoomIn: string;
      zoomOut: string;
      patientsNoun: string;
      mostFrom: string;
      emptyTitle: string;
      emptyBody: string;
      globeAria: string;
      scrollUp: string;
      scrollDown: string;
    };
    finalPatientTitle: string;
    finalPatientBody: string;
    finalPatientCta: string;
    finalClinicTitle: string;
    finalClinicBody: string;
    finalClinicCta: string;
  };
  clinics: {
    seoTitle: string;
    heroTag: string;
    heroSub: string;
    primaryCta: string;
    secondaryCta: string;
    requestLabel: string;
    requestBudget: string;
    requestTreatment: string;
    requestLanguage: string;
    requestReview: string;
    metricCaption: string;
    panelLabel: string;
    compareEyebrow: string;
    compareTitle: string;
    compareBeforeLabel: string;
    compareAfterLabel: string;
    compareCriteriaLabel: string;
    compareIntro: string;
    compareBeforeTitle: string;
    compareBeforeFoot: string;
    compareRecommended: string;
    compareAfterTitle: string;
    compareAfterFoot: string;
    compareRows: {
      title: string;
      before: string;
      after: string;
      highlight?: boolean;
    }[];
    roadmapTitle: string;
    roadmapIntro: string;
    roadmapClinicLabel: string;
    roadmapMqLabel: string;
    roadmapSteps: {
      title: string;
      clinic: string;
      mediQueue: string;
      previewHint?: string;
    }[];
    performanceTitle: string;
    metrics: { label: string; value: string; hint: string }[];
    analytics: {
      eyebrow: string;
      title: string;
      body: string;
      panelTitle: string;
      panelSubtitle: string;
      demoCaption: string;
      countryColumn: string;
      patientColumn: string;
      emptyList: string;
      highlights: { title: string; body: string }[];
    };
    finalTitle: string;
    finalBody: string;
    finalCta: string;
  };
  patients: {
    seoTitle: string;
    heroTag: string;
    heroSub: string;
    primaryCta: string;
    secondaryCta: string;
    caption: string;
    whyEyebrow: string;
    whyTitle: string;
    whyBeforeLabel: string;
    whyAfterLabel: string;
    whyCriteriaLabel: string;
    whyIntro: string;
    whyBeforeTitle: string;
    whyBeforeFoot: string;
    whyRecommended: string;
    whyAfterTitle: string;
    whyAfterFoot: string;
    whyRows: { title: string; before: string; after: string }[];
    journeyTitle: string;
    journeyIntro: string;
    journeySteps: { title: string; body: string }[];
    discoverPrivacyNote: string;
    trustTitle: string;
    trustBody: string;
    trustJci: string;
    trustNational: string;
    trustEyebrow: string;
    trustCheck1: string;
    trustCheck2: string;
    trustBadges: { title: string; subtitle: string; tag: string }[];
    finalTitle: string;
    finalBody: string;
    finalCta: string;
  };
  doctors: {
    seoTitle: string;
    eyebrow: string;
    title: string;
    intro: string;
    primaryCta: string;
    secondaryCta: string;
    caption: string;
    compareEyebrow: string;
    compareTitle: string;
    compareBeforeLabel: string;
    compareAfterLabel: string;
    compareCriteriaLabel: string;
    compareIntro: string;
    compareBeforeTitle: string;
    compareBeforeFoot: string;
    compareRecommended: string;
    compareAfterTitle: string;
    compareAfterFoot: string;
    compareRows: {
      title: string;
      before: string;
      after: string;
      highlight?: boolean;
    }[];
    featuresEyebrow: string;
    liveDemo: string;
    featuresTitle: string;
    featuresIntro: string;
    features: { id: string; title: string; body: string }[];
    roadmapTitle: string;
    roadmapIntro: string;
    roadmapDoctorLabel: string;
    roadmapMqLabel: string;
    roadmapSteps: {
      title: string;
      doctor: string;
      mediQueue: string;
      previewHint?: string;
    }[];
    trustMessage: string;
    finalTitle: string;
    finalBody: string;
    finalCta: string;
  };
  how: {
    seoTitle: string;
    eyebrow: string;
    title: string;
    intro: string;
    steps: { title: string; body: string }[];
    techTitle: string;
    techBody: string;
    pipeline: { title: string; body: string }[];
    faqEyebrow: string;
    faqTitle: string;
    faqSubtitle: string;
    faqItems: { q: string; a: string }[];
    patientCta: string;
    clinicCta: string;
    stepsKicker: string;
    stepsTitle: string;
    marketplaceBadge: string;
    faqExtraTitle: string;
    faqExtraBody: string;
    faqExtraCta: string;
  };
  team: {
    seoTitle: string;
    heroEyebrow: string;
    heroLeadBold: string;
    heroLeadLight: string;
    heroIntro: string;
    heroChip1: string;
    heroChip2: string;
    missionLabel: string;
    missionBody: string;
    visionLabel: string;
    visionBody: string;
    note: string;
    achievementChips: { label: string; detail: string }[];
    foundersEyebrow: string;
    foundersTitle: string;
    members: {
      name: string;
      roleTitle: string;
      bio: string;
      image: string;
      accent: string;
      linkedin: string;
    }[];
    socialTitle: string;
    socialEyebrow: string;
    socialIntro: string;
    visitPage: string;
    exploreAsPatient: string;
    addClinicCta: string;
    achievementsAside: string;
    socialLinks: {
      platform: "linkedin" | "instagram" | "x";
      label: string;
      hint: string;
      href: string;
    }[];
    stats?: { label: string; value: string; hint: string }[];
    valuesEyebrow: string;
    valuesTitle: string;
    values?: { title: string; body: string; icon: string }[];
    achievementsEyebrow?: string;
    achievementsTitle?: string;
    finalCtaTitle: string;
    finalCtaBody: string;
  };
  footer: {
    tagline: string;
    groups: { title: string; links: NavLink[] }[];
    copyright: string;
    sendEmail: string;
    privacyNote: string;
    medicalDisclaimer?: string;
  };
  cookie: {
    message: string;
    accept: string;
    reject: string;
    privacy: string;
  };
  legal: {
    updatedLabel: string;
    backHome: string;
    privacy: LegalDoc;
    terms: LegalDoc;
    disclaimer: LegalDoc;
  };
  previews: PreviewsContent;
  screens: ScreensContent;
};
